select PRODUCTID, PRODUCTSTANDARDPRICE, PRODUCTDESCRIPTION
from PRODUCT_T
where PRODUCTFINISH = 'Oak' and PRODUCTSTANDARDPRICE>500;

SELECT CUSTOMERNAME, CUSTOMERADDRESS
FROM CUSTOMER_T
WHERE CUSTOMERNAME LIKE '%Furniture'
ORDER BY CUSTOMERNAME;

SELECT COUNT(*)
FROM EMPLOYEE_T
WHERE EMPLOYEECITY = 'Knoxville';

SELECT CUSTOMERSTATE, COUNT(*)
FROM CUSTOMER_T
GROUP BY CUSTOMERSTATE
ORDER BY CUSTOMERSTATE;

SELECT PRODUCTFINISH
FROM PRODUCT_T
GROUP BY PRODUCTFINISH
HAVING COUNT(*)>2;

SELECT ORDERDATE, CUSTOMERNAME, CUSTOMERADDRESS, CUSTOMERCITY
FROM CUSTOMER_T INNER JOIN ORDER_T ON  ORDER_T.CUSTOMERID = CUSTOMER_T.CUSTOMERID
WHERE CUSTOMERSTATE = 'NY';